// <auto-generated />
using FinalProjectWebServerApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalProjectWebServerApp.Migrations
{
    [DbContext(typeof(AboutContext))]
    [Migration("20220418161811_aboutdbmig")]
    partial class aboutdbmig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalProjectWebServerApp.Models.Hobby", b =>
                {
                    b.Property<int>("HobbyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HobbyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Hobby");

                    b.HasData(
                        new
                        {
                            HobbyId = 11,
                            Description = "JACK",
                            StudentId = 1,
                            Title = "JACK"
                        },
                        new
                        {
                            HobbyId = 12,
                            Description = "JACK",
                            StudentId = 1,
                            Title = "JACK"
                        },
                        new
                        {
                            HobbyId = 21,
                            Description = "ALEX",
                            StudentId = 2,
                            Title = "ALEX"
                        },
                        new
                        {
                            HobbyId = 22,
                            Description = "ALEX",
                            StudentId = 2,
                            Title = "ALEX"
                        });
                });

            modelBuilder.Entity("FinalProjectWebServerApp.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId");

                    b.HasIndex("StudentId");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            ProjectId = 11,
                            Description = "JACK",
                            StudentId = 1,
                            Title = "JACK"
                        },
                        new
                        {
                            ProjectId = 12,
                            Description = "JACK",
                            StudentId = 1,
                            Title = "JACK"
                        },
                        new
                        {
                            ProjectId = 21,
                            Description = "ALEX",
                            StudentId = 2,
                            Title = "ALEX"
                        },
                        new
                        {
                            ProjectId = 22,
                            Description = "ALEX",
                            StudentId = 2,
                            Title = "ALEX"
                        });
                });

            modelBuilder.Entity("FinalProjectWebServerApp.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Name = "Jack"
                        },
                        new
                        {
                            StudentId = 2,
                            Name = "Alex"
                        });
                });

            modelBuilder.Entity("FinalProjectWebServerApp.Models.Hobby", b =>
                {
                    b.HasOne("FinalProjectWebServerApp.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProjectWebServerApp.Models.Project", b =>
                {
                    b.HasOne("FinalProjectWebServerApp.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
